### ISSUE TITLE
Prometheus Deployment for Grafana 

### ISSUE THREAD

**Issue by SharifAbdulcoder** [fuchicorp/common_jenkins#38]
Hello @fuchicorp/devops ,

Please deploy Prometheus deployment with helm chart and customize all needed information. If you have any questions feel free to add [RunBook](https://github.com/orgs/fuchicorp/projects/24)

**Comment by fsadykov** [comment]
Hello @SharifAbdulcoder ,

Is this ticket is closed? Would you please update this ticket? We don't have Prometheus deployed into our cluster.  We should integrate  Prometheus with the grafana

Thank you

**Comment by NadiraSaip** [comment]
Prometheus Deployed!
please check running below command:
sudo find / -iname '*prometheus*'

**Comment by Khuslentuguldur** [comment]
really

**Comment by fsadykov** [comment]
We will need to first take a look existing Prometheus  before deploying new Prometheus  into our cluster
